### ISSUE TITLE
Access denied for some files in nextcloud client without any apparent reason

### ISSUE THREAD

**Issue by felihommen** [nextcloud/client#13]
### Expected behaviour
All files were syncing

### Actual behaviour
Some files, are not syned. "Not synced" tab shows "access denied" for some new files for no apparent reason. This have happened once before, and the only solution founded was to remove the parent folder and recreating it
This happens on some computers, but not in others, owned by the same user. Both times in the same computers

### Steps to reproduce
1. No idea

### Server configuration
Operating system: Debian 9

Web server: nginx 1.10.3

Database: mariadb 10.1.26

PHP version: 7.0.19

nextCloud version: 12.0.3

Storage backend (external storage): local

### Client configuration
Client version: 2.3.2

Operating system: Windows 10

OS language: spanish

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: https://gist.github.com/felihommen/e32f7601e15a35e81292f8c55859b07c

2. Web server error log: https://gist.github.com/felihommen/2e97b64de38b62a978f7ed256df0e443

3. Server logfile: https://gist.github.com/felihommen/62f115edf1317586ad8ec3b7e5eb09ad

4. Config file: https://gist.github.com/felihommen/28f1a3eeafbe013db72d3f731d25acb6

5. Client gui "not synced" messages: https://s3-eu-west-1.amazonaws.com/felihommen/Nextcloud+error.pdf

**Comment by camilasan** [comment]
@felihommen do you still have this issue?

**Comment by felihommen** [comment]
No.
My server version is now 12.0.6 and as far as I know it has not happened again

**Comment by camilasan** [comment]
You should consider updating to 13. Will close it then.
