### ISSUE TITLE
Can AnyOne help me to know how to Start Contributing to this project.

### ISSUE THREAD

**Issue by richard457** [nextcloud/client#142]
Hello, I am deeply interested in contributing to this project , Please can anyone help me to get started from after cloning how to compile and add any simple functionality thank you.

**Comment by camilasan** [comment]
Hello,

You can find instructions on how to build the client here: https://doc.owncloud.org/desktop/2.1/building.html
I recommend to use QtCreator for that.
Then after you have it compiled you can look in the list of issues for something that you might find easy to start working on: https://github.com/nextcloud/client/issues

If you bump into problems you can get help by using irc (see https://docs.nextcloud.com/server/12/developer_manual/commun/index.html) or the forums: 
https://help.nextcloud.com/. Github issues are not the place for this kind of questions.

Good luck!
