### ISSUE TITLE
Add option to not use the system exclude list

### ISSUE THREAD

**Issue by rullzer** [nextcloud/client#146]
Some people want to sync everything. However on most installations they can't touch the default exclude list. So while they can exclude more. They can't exclude less.

A simple option to disable this would make sense I think.

**Comment by camilasan** [comment]
Aren't there files that should never be synced? Like the *.db ones?

**Comment by rullzer** [comment]
@camilasan yes! good point but I thin they are tracked separatly see: https://github.com/nextcloud/client/blob/master/sync-exclude.lst

**Comment by camilasan** [comment]
The PR was merged.
