### ISSUE TITLE
dolphin integration in xenial is not working

### ISSUE THREAD

**Issue by ksteinb** [nextcloud/client#147]
The dolphin integration in Ubuntu 16.04 is not working (nextcloud-client-dolphin package)

The reason is an incorrect path for the dolphin plugin.

The error message is:

Error loading plugin "nextclouddolphinactionplugin" "Die dynamische Bibliothek konnte nicht gefunden werden." 
Plugin search paths are ("/usr/lib/x86_64-linux-gnu/qt5/plugins", "/usr/bin") 
The environment variable QT_PLUGIN_PATH might be not correctly set

The files are packed into:

/usr/lib/x86_64-linux-gnu/plugins                                                                                                                                                           
/usr/lib/x86_64-linux-gnu/plugins/nextclouddolphinactionplugin.so                                                                                                                           
/usr/lib/x86_64-linux-gnu/plugins/kf5                                                                                                                                                       
/usr/lib/x86_64-linux-gnu/plugins/kf5/overlayicon
/usr/lib/x86_64-linux-gnu/plugins/kf5/overlayicon/nextclouddolphinoverlayplugin.so

this is incorrect for xenial, they should be under /usr/lib/x86_64-linux-gnu/qt5/plugins

Workaround:

sudo bash
cd /usr/lib/x86_64-linux-gnu/qt5/plugins/
ln -s ../../plugins/nextclouddolphinactionplugin.so .
cd kf5
ln -s ../../../plugins/kf5/overlayicon .

then the dolphin integration works as expected.

So please rebuild the nextcloud-client-dolphin package with the correct path

**Comment by ax1036** [comment]
another workaround:
Add this line to ~/.profile
`export QT_PLUGIN_PATH="/usr/lib/x86_64-linux-gnu/plugins/"`

**Comment by ivaradi** [comment]
The latest PPA versions should fix this problem. Please, check it out, and let me know your results.

**Comment by ax1036** [comment]
Updated, removed workaround, logged out/in: still no overlay/menus

**Comment by ksteinb** [comment]
looks like the fix did not made it into 2.3.3-20180224.205056~xenial1

qt5 is missing again from the path

Sincerly,
Klaus

**Comment by ivaradi** [comment]
The stable PPA should now contain the fix. Please, give it a try.

**Comment by ksteinb** [comment]
Am 26.02.2018 um 19:20 schrieb István Váradi:
> The stable PPA should now contain the fix. Please, give it a try.
yep, it works.

Sincerly,
Klaus
