### ISSUE TITLE
How can I auto start nextcloud without login system?

### ISSUE THREAD

**Issue by fcying** [nextcloud/client#15]
I select the "Start at system startup" , if i login system, nextcloud will autostart, without login, nextcloud will not start.

I try call /usr/bin/nextcloud in vnc startup file, it can autostart, by I need input password everytime. 
![1](https://user-images.githubusercontent.com/106934/31650554-700a7312-b34a-11e7-9cde-0df57d556c7d.jpg)

**Comment by juliushaertl** [comment]
The client will either use GNOME keyring or KWallet depending on what is installed to store your password. Try installing one of those two to store your password for the client.

**Comment by fcying** [comment]
@juliushaertl  if I login system, nextcloud can autostart and login, just start nextcloud in vnc client must input password

**Comment by juliushaertl** [comment]
So your VNC is not running on the regular session but creating its own... Then it might be an issue there. Maybe you need to start your keyring service there as well. Not a client but, so closing this.

**Comment by evdcush** [comment]
Hello,
I would like to have Nextcloud start on system boot without requiring login through the GUI.

Sometimes I need to reboot my remote PC and I have not been able to get Nextcloud to start through remote `ssh` session.

If I attempt to exec `nextcloud` in the terminal, it crashes:

```
$ nextcloud 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: dxcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

[1]    88144 abort (core dumped)  nextcloud
```

What can I do to start/launch the Nextcloud service through remote login over `ssh`?
