### ISSUE TITLE
Encrypted file is showing twice in sync protocol

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/client#153]
It is shown as uploaded (decrypted name) and downloaded (encrypted name)
![image](https://user-images.githubusercontent.com/5836855/35625132-749ae674-0691-11e8-88a4-02fe8118b3c4.png)

**Comment by tcanabrava** [comment]
Help me there :)
probabely is related to the database

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it, only #154.
