### ISSUE TITLE
Automatic Contacts Backup - only first contact reaches desktop

### ISSUE THREAD

**Issue by kaefert** [nextcloud/client#175]
I've activated the automatic backup of contacts in the android app, and they reach my server fine, but there seems to be something special about the way those backups are uploaded, since when they're downloaded to my linux desktop client (maybe the bug is with that client, not android, but I don't know) only the first contact is contained in the backup file (I checked the sync hidden files option in the desktop client)

On the server though the complete contact backups are there, just the download to the desktop client is wrong:
![screenshot from 2018-02-09](https://user-images.githubusercontent.com/1448723/36033731-1d9dccce-0db2-11e8-8866-6237415163f4.png)

Nextcloud Android app version: 2.0.1
Nextcloud server version: 12.0.5
Desktop Sync client Version 2.3.3 (Built from Git revision 57bc79 on Jan 23 2018, 06:25:38 using Qt 5.10.0, OpenSSL 1.0.2j 26 Sep 2016)

I've previously filed the issue on the android app issue tracker here:
https://github.com/nextcloud/android/issues/2124
but @tobiasKaminsky told me to file it here instead.

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/nextcloud/client/issues/138

**Comment by kaefert** [comment]
ah okey, thanks for the info. then I guess it's best to close this one.
