### ISSUE TITLE
Any way to remove the check mark by the file icon? It's reallt annoying (Mac)

### ISSUE THREAD

**Issue by mettaworldjon** [nextcloud/client#180]
Anyway to remove the check (or status mark) from folders and files? 

Mac:

<img width="101" alt="screen shot 2018-02-10 at 9 56 01 pm" src="https://user-images.githubusercontent.com/30168783/36069335-317d5524-0ead-11e8-9402-8c3973935540.png">

**Comment by rullzer** [comment]
No this is not possible. Unless you compile the client yourself.

**Comment by q2apro** [comment]
⚠️ Please reopen this. There should be an option to not display the checkmark.

Actually there is a problem with Nextcloud and Windows Explorer. 

When opening Explorer, Nextcloud goes over ALL folders in the left sidebar (folder pane) and sets green checkmarks on each of them. If you have more than 50 folders there and a normal PC, you notice how slow the Explorer gets.

There *must* be an option so Nextcloud does not touch the folder pane, in other words, does not put its green checkmark there.

Please reopen!

**Comment by q2apro** [comment]
Ah, there seems to be one way ... when installing Nextcloud, see https://github.com/nextcloud/desktop/issues/4112

But again, this should be an **option** in the Nextcloud desktop client configuration interface!

**Comment by dwheeler** [comment]
This really should be re-opened. It's pretty unacceptable from a user perspective that the "fix" for this is to uninstall and re-install the dekstop client to change the setting. If the desktop client devs would prefer not to implement this feature it would be nice to at least have some documentation on a script or cammand that can be used to disable the feature without uninstalling the app. There must be a way to remove the component post install.

**Comment by gessel** [comment]
The uninstall/reinstall trick isn't available without a GUI installer - is there a way to disable the icons in linux? Recompiling the client is fine if that's what has to be done, but certainly makes version maintenance less convenient.

The icons have, until recently, seemed appropriately sized.  The current ones are kinda insane and I'd very much prefer to have none than not be able to see the file/preview icon behind them. 

<img width="290" height="281" alt="Image" src="https://github.com/user-attachments/assets/e931a058-0909-4feb-8817-97877cb36646" />
