### ISSUE TITLE
Maybe add libgnome-keyring0 as a dependency to the nextcloud-client package?

### ISSUE THREAD

**Issue by mortie** [nextcloud/client#181]
I've just spent a couple of hours trying to figure out why the nextcloud-client from [the PPA](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) didn't use the keyring on my xubuntu 17.10 system. Seahorse worked, so I knew my gnome keyring was actually running. It turned out I was missing the package `libgnome-keyring`.

Adding that package as a dependency (at least an optional dependency) would save myself, and probably many others, many hours of debugging.

**Comment by rullzer** [comment]
cc: @ivaradi
