### ISSUE TITLE
Client not the last on main website ? 

### ISSUE THREAD

**Issue by ad1rie1** [nextcloud/client#185]
Hi, 

I see an update 2.3.4 and 2.4 is out and not avaible in the main website, the 2.3.4 is out from october  :) 

Dear,

**Comment by rullzer** [comment]
We did not release a 2.4 yet.

**Comment by ArchangeGabriel** [comment]
No, but OwnCloud did and since the current documentation on building/getting NextCloud client basically uses https://github.com/owncloud/client/, this is confusing a lot of people.

**Comment by ad1rie1** [comment]
Can i port the owncloud fix to the nextcloud client base ?
