### ISSUE TITLE
While using desktop client (AppImage) for Linux, external HDD not going into sleep mode

### ISSUE THREAD

**Issue by JosefLaumer** [nextcloud/client#186]
Hello,

while using the desktop client (AppImage) for Linux Mint 18.3, the external HDD is not spinning down anymore.
 It seems it will be regulary waked up by the client. If i close the client, the HDD goes into sleep mode after some minutes.
The android app don't cause any problems.
HDD state was checked with hdparm. HDD is 3,5" Intenso Memory Center 1TB.
Client version is 2.3.3.

Thank you in advance!

**Comment by rullzer** [comment]
This is to be expected. In the sync folder we also keep some status files (like a db of all the files with some metadata etc). So we write to it on a regular basis.

**Comment by JosefLaumer** [comment]
Thank you for your reply. But is it planned to change it in future releases, or can i change the behavior somehow? This is negative for the lifetime of my HDD since many users are on my server and most of the time at least one user is connected via client.
