### ISSUE TITLE
Unable to add patterns beginning with # to the ignore list

### ISSUE THREAD

**Issue by ad2h** [nextcloud/client#200]
When trying to add a pattern which begins with `#` (for example `#*#` which is useful for Emacs autosaves)  to the list of ignored files the pattern first seems to be added, but after confirming and opening the list again it is removed.

Version 2.3.3 on Ubuntu.

**Comment by michaelstingl** [comment]
Fixed in version 2.4.0 of upstream project: https://github.com/owncloud/client/issues/6012
