### ISSUE TITLE
Syncronizing External Samba Storage in Nextcloud with Desktop Client

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/client#201]
New file created in External Storage directly [Windows Share in System 1] is not being synced with Nextcloud Client [System 2] (even after 1 hour); After accessing the location in GUI ; Its been synced in Desktop Client as well; 

**Situation Is:**
If i create file in external storage directly; it will sync in desktop client only if i access it first via GUI in Nextcloud.

**Expected Scenario:**
Step 1: A file created in external storage
Step 2: During synchronization in Desktop client, client should request server (nextcloud server) to update the database
Step3: After updating data base, it should sync with current datas

**Comment by michaelstingl** [comment]
Server docs recommend [scanning periodically](https://docs.nextcloud.com/server/13/admin_manual/configuration_files/external_storage_configuration_gui.html#adding-files-to-external-storages). I guess there is nothing the client can do here.
