### ISSUE TITLE
[Feature request] Option to disable the "Remove all the files?" warning

### ISSUE THREAD

**Issue by leafcutterant** [nextcloud/client#207]
I get this warning message beginning with "All the files in you local sync folder "{path}" were deleted" when I delete all files. It's very annoying. Please create an option to turn this off.

**Comment by michaelstingl** [comment]
@leafcutterant see [docs](https://doc.owncloud.com/desktop/latest/advancedusage.html#configuration-file) for `promptDeleteAllFiles` option

**Comment by leafcutterant** [comment]
Thank you!

Also, I guess this should have gone to the upstream project, so I'm closing.
