### ISSUE TITLE
Error: Could NOT find Qt5WebKitWidgets

### ISSUE THREAD

**Issue by mhfaruk** [nextcloud/client#213]
**I get this error, after following the 'Windows development build' of this manual** 

-- Could NOT find Qt5WebKitWidgets (missing: Qt5WebKitWidgets_DIR)
CMake Warning at src/gui/CMakeLists.txt:313 (find_package):
  Found package configuration file:

    C:/Qt/Qt5.6.0/5.6/mingw49_32/lib/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "WebKitWidgets" config file at
  "C:/Qt/Qt5.6.0/5.6/mingw49_32/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfig.cmake"

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
CMake Error at src/gui/CMakeLists.txt:253 (add_executable):
  Target "owncloud" links to target "Qt5::WebKitWidgets" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

**Comment by rullzer** [comment]
Build with -DNO_SHIBBOLETH=1
