### ISSUE TITLE
[Error]: Entry point not found -nextcloud.exe

### ISSUE THREAD

**Issue by mhfaruk** [nextcloud/client#215]
**I have built nextcloud desktop client using QT 5.5 and Cmake 3.9 successfully but when i click on built binary i get the following errors prompted-**

1.The procedure entry point 
**_ZNSt13random_device_M_init_pretr!ERKNSt7_cxx-basic_stringlSt11char_traitslcEEE** could not be located in the dynamic link library "F:\nextcloud\client-build\bin\nextcloud.exe"

2.The procedure entry point  **_ZdlPvjcould** not be located in the dynamic link library "F:\nextcloud\client-build\bin\libnextcloudsync.dll"

3.The procedure entry point  **_ZNKSt7_cxx1112basic_stringlwSt11 char_traitslwESalwEE4dataEv** could not be located in the dynamic link library "F:\nextcloud\client-build\bin\libocsync.dll"

**Comment by mhfaruk** [comment]
**I have solved these problem by adding the "libstdc++-6.dll" library to my project folder simply.** 
but another two errors are occurred again-

1.The procedure entry point _ZN8QWEbpage10chooserFileEP9QWebFrsmeRK7Qstirng could not be located in the dynamic link library.

2.The procedure entry point ?scrollbarGeometry @Webframeadapter @@QBE?AVQRect@@W4orientation@QT@@@Z  ould not be located in the dynamic link library.

**Comment by tcanabrava** [comment]
This is not a issue with the client, but with your build (it's not finding the dll's), please find out what are your missing dll's and move it to the folder where your application should start.

**Comment by Nanoatic** [comment]
I found how to solve that, because the app wont tell which dll is missing , you have to find it yourself and add it to the same location as the executable : you have to find the missing QT class and in which dll it's located. i think this is a dll inter-dependency issue.
