### ISSUE TITLE
scary wording on big changes

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/client#216]
The desktop client has some logic to detect potential sync issues. If, for example, a backup is restored on the server, it will seem that all files are changed - but, of course, the version on the client is probably newer. The client then explains the problem to the user and presents them with two options:

**Keep Files** or **Remove all files**

Now we know users don't read and just looking at the options, there seems only one sane option: OF COURSE you want to keep your files! However, if the warning was simply triggered because you uploaded/modified a lot of files on another system, this option will undo all those changes, resulting in data loss.

I suggest we rename these options:

**Keep Local Files** or **Download New Files**

@jancborchardt @camilasan

**Comment by jancborchardt** [comment]
Sounds good! (Except only first word should be capitalized ;)
