### ISSUE TITLE
can't change wizard window header color.

### ISSUE THREAD

**Issue by mhfaruk** [nextcloud/client#223]
**i want to change wizard blue color to red color but i can't do it. I have searched for it in different ways but don't find any related issue. screenshot given following**.

![capture1](https://user-images.githubusercontent.com/37137974/37753422-05566600-2dc7-11e8-97da-96522abc7498.PNG)

**Comment by camilasan** [comment]
Please check: https://github.com/nextcloud/client/issues/238#issuecomment-381594834
