### ISSUE TITLE
Make it possible to create folders on Nc when setting up individual folder sync connections

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/client#227]
You can sync files with Nextcloud in two major ways:
* sync everything in one directory, say /Nextcloud
* sync specific Nextcloud folders to your local system, like /Documents /work /private and /projects

When creating individual folder sync connections you have to pick a local and a remote folder. But you have to create them on the server in advance - quite annoying on a fresh install. I suggest we make it possible for users to create the folder on Nextcloud with a 'new folder' button.

**Comment by jancborchardt** [comment]
Or rather, you can either:
- Choose a local folder for the sync connection first: It will then set the remote folder with the same name as the default sync connection. If it doesn’t exist, create it automatically.
- And vice versa for if you choose a remote folder first

**Comment by michaelstingl** [comment]
@jospoortvliet Strange. In the upstream project, there is a button "Create Folder". (I think for a long time, just tested with 2.4.1)

![add_folder_sync_connection_and_owncloud](https://user-images.githubusercontent.com/214010/37868728-8b41a654-2fab-11e8-8775-8053bc365b20.png)

**Comment by camilasan** [comment]
That is true. This is already done.

**Comment by jospoortvliet** [comment]
Entirely right. Not sure how I missed this...
