### ISSUE TITLE
Colour of icon against red background in windows taskbar

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/client#23]
The colour of the taskbar Nextcloud logo changes based on the status of Nextcloud sync.
But in my case the red colour almost disappears vs the red background of my laptop install.
(Windows 10)
![taskbar](https://user-images.githubusercontent.com/3051118/31895402-606f60e0-b811-11e7-8d92-f1fea348d53e.png)
The screenshot is of the green icon, which is OK but when something goes wrong the icon becomes almost invisible.

Some dynamic way of choosing the colour, taking into account the background colour or having a backdrop/shadow to guarantee visibility would help here.

**Comment by jancborchardt** [comment]
In the settings, go to »General« and check »Use monochrome icons«. Then in your case all the icons should be white.

Dynamic way of choosing the color is out of scope afaik. cc @rullzer
