### ISSUE TITLE
sync does not work if the target folder is a link (to another disk)

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/client#231]
### Actual behaviour
-Tell us what happens
sync - Action ignored

### Expected behaviour
-Tell us what should happen
sync - action  download
 
### Steps to reproduce
1. move the "photos" directory defined to a different disk
2. create  a link to where the director  was before
3.

**Comment by camilasan** [comment]
I just tried this on my machine (Linux) and it worked. Could you please check the logs? Does it say anything?
Any idea @rullzer?

**Comment by ferdiga** [comment]
I think it's a client side problem, 
neither get files synced to the client nor from the client to the server for THIS folder
activity says "ignored" for files to be downloaded and nothing for files to be uploaded.

**Comment by EorlBruder** [comment]
Could this be related to Nextcloud not syncing (symbolic) links? When I add a link in my Nextcloud-directory the client doesn't sync the link with this message: "Symbolic links are not supported in syncing". There's some discussion on the topic in this thread: https://help.nextcloud.com/t/symbolic-link-support/220/27

**Comment by camilasan** [comment]
@ferdiga My bad, I think I committed a mistake before. It doesn't work. 
@EorlBruder you are right. 

I will keep the issue #250 and will close this one.
