### ISSUE TITLE
[Feature Request] Allow multiple URLs for same nextcloud instance to facilitate sync over LAN when available.

### ISSUE THREAD

**Issue by crobarcro** [nextcloud/client#240]
A simple change which would be useful to me would be to allow multiple urls to be given to the client for the same nextcloud account, and when trying to sync, have the nextcloud client try each of them in turn until one works.

I could put the local IP address of the nextcloud instance on my LAN as the top option, and the remote url as the second. When I'm at home then syncing could happen over the LAN and elsewhere it could happen over the internet. You could probably hide all this from basic users by having an 'Advanced Config' option somehwere.

**Comment by michaelstingl** [comment]
@crobarcro Did you check [dnsmasq](https://en.wikipedia.org/wiki/Dnsmasq)?

More pointers:
- https://help.nextcloud.com/t/lan-sync-please/512/17
- https://forum.owncloud.org/viewtopic.php?t=23767#p69796
- https://github.com/owncloud/client/issues/203#issuecomment-144151410

**Comment by camilasan** [comment]
I think it makes more sense to configure a dnsmasq (often you can configure this in your router too) than to implement this on the client.
