### ISSUE TITLE
Typo in desktop client

### ISSUE THREAD

**Issue by quotengrote** [nextcloud/client#248]
See: https://github.com/nextcloud/gsoc_client/issues/19#issuecomment-380552404

**Comment by rakekniven** [comment]
Hello @quotengrote ,
the client repository does not have any file containing the string you referring.
So there is nothing to fix.

**Comment by quotengrote** [comment]
Hmm intresting, in the official build i can see it. I try building the client myself tomorrow.

**Comment by rakekniven** [comment]
Hello, any news?
I cannot see string in official build.
gsoc repo is now read only.
