### ISSUE TITLE
[Question] Using the same folder on dual boot windows / linux

### ISSUE THREAD

**Issue by SnowMB** [nextcloud/client#252]
Hello,

I'm dualbooting my machine to arch linux and windows. My nextcloud folder is on a partition reachable from both os. Right now I'm only synchronizing the folder when I'm booting linux (what I am doing most of the time).
I don't like to duplicate my data, because it would waste to much space. But sometimes I would like to upload data from windows instantly without having to reboot into linux (or using the web interface).

Can I safely activate the nextcloud synchronisation on the same folder on the windows side?  Are there any differences in how the files / configuration / temporaries are handled that could lead to errors?

**Comment by camilasan** [comment]
Hi! Please, use the forum for questions: help.nextcloud.com. Thanks!
