### ISSUE TITLE
do not sync new sibling folders of selected folders where the parent is not explicitly selected automatically

### ISSUE THREAD

**Issue by Tezcatlipoca1982** [nextcloud/client#256]
Hi guys,

I want to use Nextcloud in my company. Currentl we are using NextCloud Version 13 and the windows desktop client 2.3.3 (build 1).

We have the following folder structure:

Department A
- Customer A
--- Project A.1 (+ subfolders)
--- Project A.2 (+ subfolders)
- Customer B
--- Project B.1 (+ subfolders)
- Customer C
--- Project C.1 (+ subfolders)
- …
Department B
…
Department A and B is shared with every user. Now the user have to decide which project or customer he likes to synchronize. For example:

User A
- Synchronize Project A.2 and B.1
User B
- Synchronize Project A.2 and C.1

If the User A or B change something in Project A.2 or in the subfolders everything is fine. Both of them have all files synchronized.

If User A decides to add a new folder in “Department A” for example “Customer D” then the user B automatically get this new folder synchronized. And this is the problem. User B do not need the information about the new customer. If someone want to get the information about Customer D they have to use the client to toggle the right check box.

Greetings,
Theo

**Comment by camilasan** [comment]
Hi,

I would suggest to add the folder you don't want to sync to the list of of ignored files (General/Edit Ignored files). 

You should consider asking help from the volunteers on the forum (who can help you debug and turn it in a bug report if it is a bug or if there is really something missing, a feature request) or, if this is important for your business, get a Nextcloud subscription (https://nextcloud.com/order) and we help you fix it in a few hours or days (according to the SLA).

Thanks!
