### ISSUE TITLE
"Owncloud" displayed in Gnome lockscreen notifications.

### ISSUE THREAD

**Issue by EishInOz** [nextcloud/client#28]
Hi,

I noticed that the Gnome 3.24 lockscreen notifications shows "Owncloud" as the name of the app generating the alerts.  This doesn't appear to be an issue elsewhere.

Using version 2.3.3 of the client on Fedora 26.

**Comment by EishInOz** [comment]
Also confirmed on Gnome 3.26 on OpenSUSE Tumbleweed.
![img_0974](https://user-images.githubusercontent.com/33239282/32357221-7e3cb956-c086-11e7-8492-e1fd4a0e712d.JPG)

**Comment by BoBeR182** [comment]
Confirming bug exists on Arch Linux

**Comment by juliushaertl** [comment]
Already fixed on master by b7fa50be4c8f84f78bd9c3e6912df91897fc9442
This should be fine once a new version is released.
