### ISSUE TITLE
Nextcloud client settings dialog not using GTK theme

### ISSUE THREAD

**Issue by viggy96** [nextcloud/client#29]
The client does not use the currently set window and shell theme. It has previously done so.

**Comment by ykgmfq** [comment]
It does for me. Do you use QGnomePlatform? Note that it will look mostly like Adwaita even when you use another GTK theme.  https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#QGnomePlatform

**Comment by camilasan** [comment]
Did @ykgmfq replied helped @viggy96?
