### ISSUE TITLE
Feature Request: add context menus to documents for sharing and copying

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/client#45]
Would be nice if the desktop client would add context menus to documents for sharing and copying, like other solutions have it (sharing either with a desktop dialog similar to DB, which of would be the advanced and preferred way, or via link to the web client). 

![image](https://user-images.githubusercontent.com/295122/32993941-15ad6656-cd60-11e7-922b-0d744b74b547.png)

**Comment by guruz** [comment]
Did you try 2.4.0 beta1?
https://owncloud.org/changelog/desktop/

**Comment by MorrisJobke** [comment]
Works here:

![bildschirmfoto 2017-11-20 um 15 59 53](https://user-images.githubusercontent.com/245432/33024626-e29d96da-ce0b-11e7-95df-c9e0d6f604b0.png)


But it is only available if the file is actually on your Nextcloud. For not synced or files in a folder outside of your Nextcloud folder(s) it does not show up obviously.

**Comment by mathiasconradt** [comment]
@MorrisJobke I see, yes, I was outside of a synced folder. I guess the other solutions do a copy (to a pre-defined folder) & share in one step. I guess this isn't really necessary. Closing this issue for the moment.
