### ISSUE TITLE
Incorrectly requesting status.php file

### ISSUE THREAD

**Issue by c0fe** [nextcloud/client#7]
So I have a server with the following stats:

- CentOS 7
- Apache Webserver
- PHP 7

The Desktop NextCloud Client is requesting URL: https://subdomain.mydomain.com/owncloud/status.php and is reporting back that the file was not found. But that's a bad URL to request since the file is available (I have checked) at: https://subdomain.mydomain.com/status.php

How can I change the URL request in the Desktop Client or what can I do?

Here is my .conf file (scrubbed of any identifiable information):

https://hastebin.com/ulebokefoc.apache

**Comment by juliushaertl** [comment]
Can you check what url your client uses for the account in the client configuration file? It should of course point to `https://subdomain.mydomain.com/`. On Linux systems it is located at ~/.local/share/data/Nextcloud/nextcloud.cfg

**Comment by helmo** [comment]
I think this is a duplicate of #4

**Comment by camilasan** [comment]
Do you still have this problem with nc 13 and nc client 2.3.3?

**Comment by c0fe** [comment]
Nope, I am closing this issue.
