### ISSUE TITLE
Client does not allow to change language

### ISSUE THREAD

**Issue by baimafeima** [nextcloud/client#78]
I have installed the nextcloud client on a computer with another system language. After installing the nextcloud client, it doesn't allow me to change the language, making it impossible to configure it as I don't read that language. There surely must be a way to locally enforce a certain language when using the nextcloud client. In any case, if there is an option, make it visible so people can actually use your software.

**Comment by nickvergessen** [comment]
I think this could be made available via the `nextcloud.cfg` file?
Or even as a parameter on the command line.

**Comment by juliushaertl** [comment]
You can select the language by setting either LANGUAGE (UNIX) or LANG (windows) environment variable.

**Comment by baimafeima** [comment]
> You can select the language by setting either LANGUAGE (UNIX) or LANG (windows) environment variable.

Could you please advise where to do that? There is no setting in the nextcloud client that would allow me to do that.

**Comment by dreua** [comment]
@baimafeima The procedure depends on your operating system and the language you want to use. If you want someone to help you, you have to provide these details. Furthermore you might be able to help yourself by searching for "how to set environment variable on <your os here>" and setting the LANG and LANG variables to some 2-letter code that might fit your desired language.

@ others: I think a language selection feature it would be a good addition to nextcloud. Most desktop applications (intended for users without admin-skills) do have such a feature which defaults to "System setting".

**Comment by baimafeima** [comment]
@juliushaertl I am still not sure why you closed this issue. This is a feature request and unless the nextcloud client has this feature I am not able to help clients set up nextcloud including `nextcloud client` on their various machines but will have to use another product. 
@dreua Thanks for your instructions but I am not looking into any specific solution here but a general solution which easily allows to set the `nextcloud client` language either during or after installation.

**Comment by unalignedcoder** [comment]
I agree changing language should be another of those obvious settings the nextcloud/owncloud clients strangely miss. 

I have a Russian computer at work which makes the nextcloud interface confusing to me, but there is no easy way to change this on windows. 

Environment variables are certainly not a solution, even if they worked, they would affect a plethora of other apps who shouldn't be confused as to what is the language of the OS.

The only solution I've found is to delete the `client_ru.qm` file from the nextCloud folder (or whatever other language is imposed on you). Unfortunately this gets re-created every time you update the app.

**Comment by dreua** [comment]
I think they won't reopen this because it does not sound like a feature request, maybe we will have more luck with a dedicated feature request: #111

**Comment by ftoledo** [comment]
AppImage v3.1.1 dont get the lang from OS Debian gnu/linux (buster xfce4) 

```
ragnarok@hp:~/AppImage$ locale
LANG=es_AR.UTF-8
LANGUAGE=es_AR:es
LC_CTYPE="es_AR.UTF-8"
LC_NUMERIC="es_AR.UTF-8"
LC_TIME="es_AR.UTF-8"
LC_COLLATE="es_AR.UTF-8"
LC_MONETARY="es_AR.UTF-8"
LC_MESSAGES="es_AR.UTF-8"
LC_PAPER="es_AR.UTF-8"
LC_NAME="es_AR.UTF-8"
LC_ADDRESS="es_AR.UTF-8"
LC_TELEPHONE="es_AR.UTF-8"
LC_MEASUREMENT="es_AR.UTF-8"
LC_IDENTIFICATION="es_AR.UTF-8"
LC_ALL=

```

![Captura de pantalla_2021-01-27_16-01-27](https://user-images.githubusercontent.com/95441/106040521-579c2800-60b9-11eb-9959-6d2546309777.png)

**Comment by ner00** [comment]
Delete all `.qm` files from the `i18n` folder, except the language you want. If you want English (US), just delete the entire `i18n` folder. It's really strange that this kind of basic stuff goes years in the back burner, especially considering the hybridization of half-translated client releases.

**Comment by mocmichal** [comment]
thanks, that is very stupid solution for such software, but it works !

**Comment by ner00** [comment]
Unfortunately you'll have to repeat this after every update.

**Comment by ner00** [comment]
> You can select the language by setting either LANGUAGE (UNIX) or LANG (windows) environment variable.

@juliushaertl This is hardly a motive to close the issue and ignore is as a feature/enhancement request. 

Anybody else from the team can reopen this so we don't have to create a duplicate issue?

Thanks!
@mgallien @claucambra @DimitriPapadopoulos @allexzander @camilasan

**Comment by dreua** [comment]
#111 is open for over 5 years now 🤷

**Comment by ner00** [comment]
> #111 is open for over 5 years now 🤷

Ducking hell, there's no point then 🤣🤣🤣

**Comment by Sylvain303** [comment]
```bash
LANGUAGE=fr ./Nextcloud-3.13.0-x86_64.AppImage
```

worked for me.

**Comment by ner00** [comment]
> > You can select the language by setting either LANGUAGE (UNIX) or LANG (windows) environment variable.
> 
> [@juliushaertl](https://github.com/juliushaertl) This is hardly a motive to close the issue and ignore it as a feature/enhancement request.
> 
> Anybody else from the team can reopen this so we don't have to create a duplicate issue?
> 
> Thanks! [@mgallien](https://github.com/mgallien) [@claucambra](https://github.com/claucambra) [@DimitriPapadopoulos](https://github.com/DimitriPapadopoulos) [@allexzander](https://github.com/allexzander) [@camilasan](https://github.com/camilasan) [@claell](https://github.com/claell)

Yearly OS workaround show (idgaf anymore)

**Comment by ner00** [comment]
I'd be grateful if someone just deleted nextcloud from the world and moved on to the next cloud. That easy.

**Comment by ner00** [comment]
> Delete all `.qm` files from the `i18n` folder, except the language you want. If you want English (US), just delete the entire `i18n` folder. It's really strange that this kind of basic stuff goes years in the back burner, especially considering the hybridization of half-translated client releases.

Whoop-de-do
