### ISSUE TITLE
Make Ubuntu packages

### ISSUE THREAD

**Issue by enoch85** [nextcloud/client#8]
Same as here: https://github.com/nextcloud/client_theming#installing-on-ubuntu

cc @ivaradi

**Comment by ivaradi** [comment]
As I think it would be unwise to produce packages from both repositories into the same PPA, the question arises how we shall coordinate the packaging of the two repositories. I can see two options:

1. The package from this repository goes into a third PPA (we have a "stable" one, a "beta", so it could be "alpha") until this one stabilizes. At that point the build of client_theming should be stopped and this one should be redirected to the existing PPAs.
1. The build of client_theming is stopped right now and this one will be delivered into the "beta" PPA for the time being.

What is your opinion?

**Comment by jospoortvliet** [comment]
I'm guessing this replaces the theming one as soon as the theming is merged in here and that'd be the day to switch over building (option 2). Right @rullzer ?

**Comment by enoch85** [comment]
@ivaradi I think option 1 is the best. You never know how long time the development of this will take.

**Comment by ivaradi** [comment]
I have started to work on Debian support, but it seems that the sources still contain the "ownCloud" name and the output files, binaries, etc. are also named so. 

What are the plans regarding this? Will all references to ownCloud in the source code be changed to Nextcloud or will the theming directory approach (as in the nextcloud-client repo) be used?

**Comment by enoch85** [comment]
@ivaradi I don't it's worth the time to put effort in to something that is still named ownCloud IMHO.

> What are the plans regarding this? Will all references to ownCloud in the source code be changed to Nextcloud or will the theming directory approach (as in the nextcloud-client repo) be used?

My guess is that this will be the new Nextcloud-original client, so no more theming.

**Comment by ivaradi** [comment]
I have implement the Debian support, but cannot push to the repository. Could you grant me access?

**Comment by enoch85** [comment]
I don't control this repo, but maybe @rullzer does?

**Comment by e-alfred** [comment]
Are there already packages for the client with encryption included?

**Comment by ivaradi** [comment]
Unfortunately, not. (I have no access to the repository yet.)

**Comment by enoch85** [comment]
@jospoortvliet Please approve @ivaradi if you think it's OK. He's responsible for the Ubuntu PPA in the theming repo.

**Comment by jospoortvliet** [comment]
Wha? The encryption stuff is all in the open - https://github.com/nextcloud/client/tree/clientSideEncryptionV3

😺

**Comment by ivaradi** [comment]
The actual problem is that I cannot push to the repository a new branch, so I cannot create a pull request for my changes to enable the Travis build for the Ubuntu/Debian packages.

(Maybe I could create a fork and probably I could create a pull request, but using only a branch would be more convenient and possibly more flexible as well.)

**Comment by Iolaum** [comment]
@ ivaradi Creating a fork and cloning it locally should give you all the flexibility you want up to the step where you create a Pull Request - unless I 'm missing something.

[Example Workflow](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository): At your local machine you should have two remotes. The origin will be your fork and another one - say upstream - will be this repository. You pull updates from here by pulling from upstream remote and then push them - along with your new code - to the origin remote (which is your fork). Once done you create a Pull request from the github UI or just point Travis to your fork until your PR gets merged.

**Comment by ivaradi** [comment]
@lolaum Well, for one thing, tags are not transferred from a forked repo. It probably is no big deal in this case, but it tells me that forking might have other restrictions as well compared to branches.

Anyway, I created a fork and a pull request (#88 ) with my changes. However, could someone enable Travis for this repo? @rullzer, @jospoortvliet ?

**Comment by Iolaum** [comment]
You can append the `--tags` option to pull/fetch/push tags between remotes.

**Comment by ivaradi** [comment]
@lolaum Yes, you can push tags to the forked repo. However, when you create a pull request on the upstram from your fork and it is eventually merged, the tags will not get to the upstream.

**Comment by enoch85** [comment]
Any update here? I saw that the Drone PR got merged, I guess this issue is solved with that PR?

**Comment by ivaradi** [comment]
Yes, the Ubuntu and Debian packages are being built, so this issue is done.
