### ISSUE TITLE
desktop client on OSX help link issue

### ISSUE THREAD

**Issue by franckl** [nextcloud/client#82]
![image](https://user-images.githubusercontent.com/3875803/33724664-571be77a-db70-11e7-9f1e-a43ad0ea7582.png)
The help button sends me to https://docs.nextcloud.com/desktop/2.2/ and this link is dead.

I am using the latest client version 2.3.3 build 84

**Comment by franckl** [comment]
sorry just found this one in another repo
https://github.com/nextcloud/client_theming/issues/165

**Comment by efx** [comment]
As of 2.2.3 on macOS, I am taken to the correct URL.
<img width="763" alt="screen shot 2018-02-07 at 9 16 27 am" src="https://user-images.githubusercontent.com/472721/35921051-9cef2e0e-0be7-11e8-8b75-b5b8ea2c23c8.png">
Link takes me to: https://docs.nextcloud.com/desktop/2.2/

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/client/pull/141
