### ISSUE TITLE
E2E private key not updated after logout/login leading to unreadable files downloaded

### ISSUE THREAD

**Issue by stratoss** [nextcloud/client#98]
Downloading encrypted file from the server is unreadable (just a hash name w/o extension). I'm using the Linux client version 2.3.2

## Steps to reproduce

1. Set-up encryption via the android app and upload a file (working fine on the desktop)
2. Delete the keys from the server like [this](https://github.com/nextcloud/android/issues/1870#issuecomment-352676731)
3. Delete the encrypted folders via the desktop client
4. Re-install the android app
5. Re-setup the encryption via the android app
6. log-out/log-in via the desktop client
7. Encrypt a folder with the same name as before via the android app
8. File not readable after the desktop client sync.

**Comment by stratoss** [comment]
Tried to re-start the desktop app & remove the encrypted folder from the "sync" list which removed it locally and then re-synced it. Same unreadable file has been downloaded.

**Comment by tcanabrava** [comment]
desktop client doesn't have e2e yet, I'm working on that.

**Comment by stratoss** [comment]
@tcanabrava that's strange, yesterday when I initially tested the E2E the images I encrypted were sync'ed with the desktop just fine (even wasn't asked for the key pass for some reason).

How is that possible?

**Comment by tcanabrava** [comment]
It's not possible, I guess you did a wrong test, there's zero code on the client/master for that, the code is currently in the branch clientSideEncryptionV3. but upload and dowloadn are still missing so you would still have errors, please don't test it yet unless you wanna help hacking.

**Comment by stratoss** [comment]
Will check it out for sure. Thanks :thumbsup:
